---
# # # # # # # # # #
#  K i k o f r i  #
# # # # # # # # # #

# Basic
name: "R h i a n n a n"
description: "Is online"

# URL
url: " "
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "about"
   href: "/about"

 - name: "projects"
   href: "/projects"

 - name: "Résumé"
   href: "/resume"

# Actually add refs to icons somehow
nav-icons:
 - name: "email"
   desc: "Email me!"
   href: "mailto:rhiannanb97@gmail.com"
   icon: "icons/envelope.svg"
 - name: "twitter"
   desc: "RT all of my golden tweets"
   href: "https://twitter.com/blood_mouth"
   icon: "icons/twitter.svg"
 - name: "github"
   desc: "Judge my code"
   href: "https://github.com/rhiannanberry"
   icon: "icons/code.svg"
 - name: "itch.io"
   desc: "Play my games"
   href: "idr"
   icon: "icons/gamepad.svg"

pagination: false
  
# Sass
sass:
 style: :compressed
 mixins: :compressed

# Excerpt
excerpt_separator: <!-ex->

#Gems
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "projects"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
---
